'use client'

import { useEffect, useState } from 'react'
import { Pencil, Plus, Star, Trash2, UserRound, X } from 'lucide-react'
import { useLanguage } from '@/hooks/useLanguage'
import { guideService } from '@/services/guides/guideService'
import type { Guide } from '@/types'

const blank: Partial<Guide> & { name: string } = { name: '', nameAr: '', city: 'Cairo', language: 'English, Arabic', specialty: 'Egyptology', rating: '5.0', reviews: 0, price: 50, image: '/images/guides/layla.png', verified: true, bio: '', bioAr: '', availability: true, assignedTours: 0 }

export function GuideWorkspace() {
  const { locale, isRtl } = useLanguage()
  const [guides, setGuides] = useState<Guide[]>([])
  const [editing, setEditing] = useState<(Partial<Guide> & { name: string }) | null>(null)
  useEffect(() => setGuides(guideService.list()), [])
  const save = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing?.name.trim()) return; setGuides(guideService.save(editing, editing.id)); setEditing(null) }
  return <section className="flex flex-col gap-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-accent">People & expertise</p><h2 className="mt-1 text-2xl font-bold">Guides directory</h2><p className="mt-1 text-sm text-muted-foreground">Manage the local experts travelers meet across Egypt.</p></div><button onClick={() => setEditing({ ...blank })} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground"><Plus data-icon="inline-start" /> Add guide</button></div>
    {guides.length === 0 ? <div className="rounded-2xl border border-dashed border-border p-12 text-center"><UserRound className="mx-auto text-muted-foreground" /><p className="mt-3 font-semibold">No guides yet</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{guides.map((guide) => <article key={guide.id} className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex gap-4 p-5"><img src={guide.image} alt={guide.name} className="size-20 rounded-2xl object-cover" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="font-bold">{locale === 'ar' ? guide.nameAr : guide.name}</h3><p className="text-xs text-muted-foreground">{guide.city} · {guide.specialty}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${guide.availability ? 'bg-secondary text-secondary-foreground' : 'bg-muted text-muted-foreground'}`}>{guide.availability ? 'Available' : 'Busy'}</span></div><div className="mt-3 flex items-center gap-3 text-xs"><span className="inline-flex items-center gap-1 font-semibold"><Star className="size-3 fill-accent text-accent" /> {guide.rating} ({guide.reviews})</span><span className="text-muted-foreground">{guide.language}</span></div></div></div><div className="flex items-center justify-between border-t border-border px-5 py-3 text-xs"><span className="font-semibold">${guide.price}/day · {guide.assignedTours ?? 0} tours</span><div className="flex gap-1"><button aria-label={`Edit ${guide.name}`} onClick={() => setEditing({ ...guide })} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil className="size-4" /></button><button aria-label={`Delete ${guide.name}`} onClick={() => { if (window.confirm(`Delete ${guide.name}?`)) setGuides(guideService.remove(guide.id)) }} className="rounded-lg p-2 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-4" /></button></div></div></article>)}</div>}
    {editing && <div className="fixed inset-0 z-50 flex items-end justify-center bg-primary/30 p-0 sm:items-center sm:p-6"><form onSubmit={save} dir={isRtl ? 'rtl' : 'ltr'} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-card p-6 shadow-2xl sm:rounded-3xl"><div className="flex items-center justify-between"><div><h3 className="text-xl font-bold">{editing.id ? 'Edit guide' : 'Add guide'}</h3><p className="text-sm text-muted-foreground">Profile, availability, and expertise.</p></div><button type="button" onClick={() => setEditing(null)} aria-label="Close"><X /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{([['name','Name'],['nameAr','Arabic name'],['city','City'],['language','Languages'],['specialty','Specialization'],['price','Daily rate']] as const).map(([key,label]) => <label key={key} className="flex flex-col gap-2 text-xs font-semibold">{label}<input required={key === 'name'} type={key === 'price' ? 'number' : 'text'} value={String(editing[key] ?? '')} onChange={(e) => setEditing({ ...editing, [key]: key === 'price' ? Number(e.target.value) : e.target.value })} className="rounded-xl border border-input bg-background px-3 py-3 text-sm font-normal outline-none focus:ring-2 focus:ring-ring" /></label>)}<label className="flex flex-col gap-2 text-xs font-semibold sm:col-span-2">Bio<textarea value={editing.bio ?? ''} onChange={(e) => setEditing({ ...editing, bio: e.target.value })} className="min-h-24 rounded-xl border border-input bg-background px-3 py-3 text-sm font-normal outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={editing.availability ?? true} onChange={(e) => setEditing({ ...editing, availability: e.target.checked })} /> Available for bookings</label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={() => setEditing(null)} className="rounded-xl border border-border px-4 py-3 text-sm font-semibold">Cancel</button><button className="rounded-xl bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground">Save guide</button></div></form></div>}
  </section>
}
